In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences

sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size

voc_size =10000

In [5]:
# One hot representation

one_hot_rep = [one_hot(words, voc_size)for words in sent]


In [6]:
one_hot_rep

[[3704, 7149, 3705, 7103],
 [3704, 7149, 3705, 6293],
 [3704, 5505, 3705, 1897],
 [9545, 3148, 2934, 7876, 3157],
 [9545, 3148, 2934, 7876, 2169],
 [4987, 3704, 4562, 3705, 4843],
 [555, 3072, 8550, 7876]]

In [7]:
### word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)

In [10]:
embedded_docs

array([[   0,    0,    0,    0, 3704, 7149, 3705, 7103],
       [   0,    0,    0,    0, 3704, 7149, 3705, 6293],
       [   0,    0,    0,    0, 3704, 5505, 3705, 1897],
       [   0,    0,    0, 9545, 3148, 2934, 7876, 3157],
       [   0,    0,    0, 9545, 3148, 2934, 7876, 2169],
       [   0,    0,    0, 4987, 3704, 4562, 3705, 4843],
       [   0,    0,    0,    0,  555, 3072, 8550, 7876]], dtype=int32)

In [11]:
### feature represntation

dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')
model.build(input_shape=(None, sent_length))

d:\RNN\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 406ms/step


array([[[ 0.00023205,  0.00650804,  0.01739437,  0.02148289,
          0.00334876, -0.01946875,  0.02482942, -0.03524826,
         -0.03840407, -0.03941648],
        [ 0.00023205,  0.00650804,  0.01739437,  0.02148289,
          0.00334876, -0.01946875,  0.02482942, -0.03524826,
         -0.03840407, -0.03941648],
        [ 0.00023205,  0.00650804,  0.01739437,  0.02148289,
          0.00334876, -0.01946875,  0.02482942, -0.03524826,
         -0.03840407, -0.03941648],
        [ 0.00023205,  0.00650804,  0.01739437,  0.02148289,
          0.00334876, -0.01946875,  0.02482942, -0.03524826,
         -0.03840407, -0.03941648],
        [ 0.00981015,  0.02948823, -0.0376063 , -0.03891926,
         -0.02224449, -0.04665659,  0.02393327, -0.04992318,
          0.00161669,  0.0357582 ],
        [-0.04415913, -0.0294209 ,  0.04829038, -0.00733837,
          0.04686951, -0.02232244, -0.00770424,  0.03192521,
          0.01072263,  0.02874755],
        [ 0.04325804, -0.00245934, -0.02959253, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 3704, 7149, 3705, 7103], dtype=int32)